name: pull-request
on:
  pull_request:
    branches:
      - develop

jobs:
  tox:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    runs-on: ubuntu-latest
    if: github.repository == 'NHSDigital/nhs-context-logging'
    permissions:
      contents: write
      checks: write
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0

      - name: print branch info
        run: |
          git branch
          echo "GITHUB_HEAD_REF=${GITHUB_HEAD_REF}"
          echo "GITHUB_BASE_REF=${GITHUB_BASE_REF}"
          git log --oneline -n 10

      - name: clean
        run: |
          git clean -fdx
          find . -type f | xargs chmod g+w

      - name: merge into base_branch
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo base branch "${{ github.base_ref }}"
          echo pr branch "${GITHUB_HEAD_REF}"
          git checkout "${{ github.base_ref }}"
          git checkout -b "merging-${{ github.event.number }}"
          git merge --ff-only "${{ github.event.pull_request.head.sha }}"

      - name: setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: setup poetry
        uses: abatilo/actions-poetry@0dd19c9498c3dc8728967849d0d2eae428a8a3d8
        with:
          poetry-version: 2.2.1

      - name: add poetry plugins
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]"
        env:
          POETRY_INSTALLER_ONLY_BINARY: ":all:"

      - name: install dependencies
        run: poetry install --with dev --no-interaction --sync
        env:
          POETRY_INSTALLER_ONLY_BINARY: ":all:"

      - name: tox
        run: poetry run tox

  coverage:
    runs-on: ubuntu-latest
    if: github.repository == 'NHSDigital/nhs-context-logging'
    permissions:
      contents: write
      checks: write
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0

      - name: print branch info
        run: |
          git branch
          echo "GITHUB_HEAD_REF=${GITHUB_HEAD_REF}"
          echo "GITHUB_BASE_REF=${GITHUB_BASE_REF}"
          git log --oneline -n 10

      - name: clean
        run: |
          git clean -fdx
          find . -type f | xargs chmod g+w

      - name: secrets-check
        run: make check-secrets

      - name: merge into base_branch
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        run: |
          echo base branch "${{ github.base_ref }}"
          echo pr branch "${GITHUB_HEAD_REF}"
          git checkout "${{ github.base_ref }}"
          git checkout -b "merging-${{ github.event.number }}"
          git merge --ff-only "${{ github.event.pull_request.head.sha }}"

      - name: setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.14"

      - name: setup poetry
        uses: abatilo/actions-poetry@0dd19c9498c3dc8728967849d0d2eae428a8a3d8
        with:
          poetry-version: 1.5.1

      - name: add poetry plugins
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]"

      - name: cache virtualenv
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            .venv
          key: ${{ runner.os }}-poetry-v2-py${{ matrix.python-version }}-${{ hashFiles('./poetry.lock') }}

      - name: git reset
        run: git reset --hard

      - name: install dependencies
        run: make install-ci

      - name: black
        run: make black-check

      - name: code coverage
        run: make coverage-ci

      - name: code coverage report
        if: ${{ github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork  }}
        uses: orgoro/coverage@3f13a558c5af7376496aa4848bf0224aead366ac
        with:
          coverageFile: reports/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 0.70

      - name: setup java
        if: ${{ !github.event.pull_request.head.repo.fork && (success() || failure()) }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: "corretto"
          java-version: "17"

      - name: provision sonar-scanner
        if: ${{ !github.event.pull_request.head.repo.fork && (success() || failure()) }}
        run: |
          export SONAR_VERSION="8.0.1.6346"
          wget -q   --max-redirect=0 "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_VERSION}.zip" -O sonar-scanner.zip
          unzip -q ./sonar-scanner.zip
          mv ./sonar-scanner-${SONAR_VERSION} ./sonar-scanner
          scripts/sonar_tests.py

      - name: run sonar scan
        if: ${{ !github.event.pull_request.head.repo.fork && (success() || failure()) }}
        run: |
          PATH="$PWD/sonar-scanner/bin:$PATH"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            git checkout "${GITHUB_HEAD_REF}"
            sonar-scanner -Dsonar.pullrequest.branch="{{ github.event.pull_request.head.sha }}" -Dsonar.pullrequest.base="{{ github.event.pull_request.base.sha }}" -Dsonar.pullrequest.key="${{ github.event.number }}"
          else
            sonar-scanner
          fi    
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: archive reports
        if: ${{ !github.event.pull_request.head.repo.fork && (success() || failure()) }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: reports
          path: reports/**/*

      - name: publish junit reports
        if: success() || failure()
        uses: mikepenz/action-junit-report@bccf2e31636835cf0874589931c4116687171386
        with:
          check_name: junit reports
          report_paths: reports/junit/*.xml

  lint:
    runs-on: ubuntu-latest
    if: github.repository == 'NHSDigital/nhs-context-logging'
    permissions:
      contents: write
      checks: write
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0

      - name: clean
        run: |
          git clean -fdx

      - name: secrets-check
        run: make check-secrets

      - name: merge into base_branch
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        run: |
          echo base branch "${{ github.base_ref }}"
          echo pr branch "${GITHUB_HEAD_REF}"
          git checkout "${{ github.base_ref }}"
          git checkout -b "merging-${{ github.event.number }}"
          git merge --ff-only "${{ github.event.pull_request.head.sha }}"

      - name: setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.10"

      - name: setup poetry
        uses: abatilo/actions-poetry@0dd19c9498c3dc8728967849d0d2eae428a8a3d8
        with:
          poetry-version: 1.5.1

      - name: add poetry plugins
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]"

      - name: cache virtualenv
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            .venv
          key: ${{ runner.os }}-poetry-v2-py3.10-${{ hashFiles('./poetry.lock') }}

      - name: git reset
        run: git reset --hard

      - name: install dependencies
        run: make install-ci

      - name: black
        run: make black-check

      - name: ruff
        run: make ruff-ci

      - name: mypy
        run: make mypy

      - name: shellcheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38
        with:
          ignore_paths: .venv build
          ignore_names: git-secrets
        env:
          SHELLCHECK_OPTS: -f gcc -e SC1090,SC1091

      - name: test next version
        run: |
          version="v$(poetry version patch | rev | cut -d' ' -f1 | rev)"
          echo "RELEASE_VERSION=$version" >> $GITHUB_ENV
          echo "${version}"

  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'NHSDigital/nhs-context-logging' && github.actor != 'dependabot[bot]' && !github.event.pull_request.head.repo.fork
    permissions:
      contents: write
      checks: write
      pull-requests: write
    needs:
      - coverage
      - lint
      - tox
    steps:
      - name: checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0

      - name: print branch info
        run: |
          git branch
          echo "GITHUB_HEAD_REF=${GITHUB_HEAD_REF}"
          echo "GITHUB_BASE_REF=${GITHUB_BASE_REF}"
          git log --oneline -n 10

      - name: clean
        run: |
          git clean -fdx
          find . -type f | xargs chmod g+w

      - name: merge into base_branch
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        run: |
          echo base branch "${{ github.base_ref }}"
          echo pr branch "${GITHUB_HEAD_REF}"
          git checkout "${{ github.base_ref }}"
          git checkout -b "merging-${{ github.event.number }}"
          git merge --ff-only "${{ github.event.pull_request.head.sha }}"

      - name: setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.10"

      - name: setup poetry
        uses: abatilo/actions-poetry@0dd19c9498c3dc8728967849d0d2eae428a8a3d8
        with:
          poetry-version: 1.5.1

      - name: add poetry plugins
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]"

      - name: poetry build
        run: |
          poetry build --format=wheel

      - name: poetry config
        env:
          TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi "${TEST_PYPI_TOKEN}"

      - name: poetry test publish
        run: poetry publish -r testpypi
  
  slack-notification:
    runs-on: ubuntu-latest
    needs:
      - tox
      - coverage
      - lint
    if: ${{ always() && github.repository == 'NHSDigital/nhs-context-logging' && github.triggering_actor == 'dependabot[bot]' && contains(needs.*.result, 'failure') }}
    steps:
      - name: Slack Notification
        uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95 #v3.0.1
        with:
          webhook: ${{ secrets.DEPENDABOT_SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":alarm: DEPENDABOT PR FAILED :alarm:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Checks failed for ${{ github.repository }}:${{ github.ref }} in <https://github.com/${{ github.repository }}/pull/${{ github.event.number }}|PR #${{ github.event.number }}>"
                  }
                }
              ]
            }